services:
  bingosim.web:
    image: bingosim.web
    build:
      context: .
      dockerfile: BingoSim.Web/Dockerfile

  bingosim.worker:
    image: bingosim.worker
    build:
      context: .
      dockerfile: BingoSim.Worker/Dockerfile

